/**
 * Phase 6 settlement lifecycle (SETTLEMENT entity).
 * SUBMITTED ≠ CONFIRMED. Failed RPC must never mark funds settled.
 */
export const SETTLEMENT_STATES = [
  "DATA_FINALIZING",
  "FINAL",
  "RESULT_CALCULATED",
  "RESULT_REVIEWED",
  "RESULT_REJECTED",
  "RESULT_APPROVED",
  "SETTLEMENT_APPROVED",
  "SETTLEMENT_PREPARED",
  "SETTLEMENT_SUBMITTED",
  "SETTLEMENT_CONFIRMED",
  "SETTLEMENT_FAILED",
  "VOIDED",
] as const;

export type SettlementState = (typeof SETTLEMENT_STATES)[number];

export const SETTLEMENT_TRANSITIONS: ReadonlyArray<readonly [SettlementState, SettlementState]> = [
  ["DATA_FINALIZING", "FINAL"],
  ["FINAL", "RESULT_CALCULATED"],
  ["RESULT_CALCULATED", "RESULT_REVIEWED"],
  ["RESULT_CALCULATED", "RESULT_REJECTED"],
  ["RESULT_REVIEWED", "RESULT_APPROVED"],
  ["RESULT_REVIEWED", "RESULT_REJECTED"],
  ["RESULT_REJECTED", "RESULT_CALCULATED"],
  ["RESULT_APPROVED", "SETTLEMENT_APPROVED"],
  ["SETTLEMENT_APPROVED", "SETTLEMENT_PREPARED"],
  ["SETTLEMENT_PREPARED", "SETTLEMENT_SUBMITTED"],
  ["SETTLEMENT_SUBMITTED", "SETTLEMENT_CONFIRMED"],
  ["SETTLEMENT_SUBMITTED", "SETTLEMENT_FAILED"],
  ["SETTLEMENT_FAILED", "SETTLEMENT_SUBMITTED"],
  ["FINAL", "VOIDED"],
  ["RESULT_CALCULATED", "VOIDED"],
  ["RESULT_REVIEWED", "VOIDED"],
  ["RESULT_REJECTED", "VOIDED"],
];
